### ISSUE TITLE
gcloud needs better error reporting

### ISSUE THREAD

**Issue by apennebaker-ni** [GoogleCloudPlatform/gcloud-maven-plugin#10] opened 2015-03-30 18:56 UTC
The Maven gcloud plugin needs better error reporting. No matter how I configure my software stack, mvn gcloud:run reports:

INFO: Successfully processed /Users/apennebaker/Desktop/src/users-ws/users-impl/target/users-impl-1.22.0-SNAPSHOT/WEB-INF/appengine-web.xml
[ERROR] Error: gcloud app xxx exit code is: 1

mvn -X doesn't give any more detail.

**Comment by ludoch** [comment] 2015-04-29 15:13
Can you give the entire output with the X parameter?
Also the output of
gcloud version
and the plugin version in your pom.xml

I cannot reproduce...

**Comment by derekberube** [comment] 2015-05-06 22:33
Here is the error that I see:

[ERROR] Failed to execute goal com.google.appengine:gcloud-maven-plugin:1.9.17a:run (default-cli) on project servicedesk: Error: gcloud app xxx exit code is: 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.appengine:gcloud-maven-plugin:1.9.17a:run (default-cli) on project servicedesk: Error: gcloud app xxx exit code is: 1
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error: gcloud app xxx exit code is: 1
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.startCommand(AbstractGcloudMojo.java:273)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:287)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException


Here is the information from my POM file.

<plugin>
   <groupId>com.google.appengine</groupId>
   <artifactId>gcloud-maven-plugin</artifactId>
   <version>1.9.17a</version>
   <configuration>
      <verbosity>debug</verbosity>
      <log_level>debug</log_level>
   </configuration>
</plugin>

Here is the cloud version information:

DerekBerubesMBP:Wildstar ServiceDesk Maven derekberube$ gcloud version
Google Cloud SDK 0.9.58

alpha 2015.04.09
app 2015.04.29
app-engine-go-darwin-x86_64 1.9.19
app-engine-java 1.9.19
app-engine-python 1.9.19
app-engine-python-extras 1.9.18
beta 2015.04.21
bq 2.0.18
bq-nix 2.0.18
compute 2015.04.29
core 2015.04.29
core-nix 2014.10.20
dns 2015.04.29
gae-java 1.9.19
gae-java-nix 1.9.10
gae-python 2014.05.06
gae-python-launcher-mac 1.9.19
gcloud 2015.04.29
gcloud-extensions-darwin-x86_64 0.15.0
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.12
gsutil-nix 4.6
preview 2015.04.29
sql 2015.04.09

The mvn -X gcloud:run output is contained in the Maven Output.txt file which is available at the following location:

https://dl.dropboxusercontent.com/u/39676662/Maven%20Output.txt

**Comment by derekberube** [comment] 2015-05-06 22:40
The following looks to be germane.

May 06, 2015 5:27:58 PM com.google.apphosting.utils.config.AppEngineWebXmlReader readAppEngineWebXml
INFO: Successfully processed /Users/derekberube/Documents/Programming/Java/Wildstar ServiceDesk Maven/target/servicedesk-1.0-SNAPSHOT/WEB-INF/appengine-web.xml
[INFO] Running python -S /Users/derekberube/google-cloud-sdk/lib/googlecloudsdk/gcloud/gcloud.py --project=wildstarservicedesk-hrd --verbosity=debug preview app run /Users/derekberube/Documents/Programming/Java/Wildstar ServiceDesk Maven/target/servicedesk-1.0-SNAPSHOT --log-level=debug
[INFO] DEBUG: Running gcloud.preview.app.run with Namespace(__calliope_internal_deepest_parser=ArgumentParser(prog='gcloud.preview.app.run', usage=None, description="*(BETA)* This command is used to run one or more of your modules in the local\ndevelopment application server.  This allows you to test and debug your app\nbefore deploying.  As an input it takes one or more ``RUNNABLES'' that should\nbe run locally.  A ``RUNNABLE'' can be a module's .yaml file, or a directory.\nIf given a directory, all modules found will be run.  You can run multiple\nmodules at the same time, even if they are implemented in different languages.", version=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=False), admin_host=None, allow_skipped_files=False, api_host=None, appidentity_email_address=None, appidentity_private_key_path=None, auth_domain='gmail.com', blobstore_path=None, clear_datastore=False, cmd_func=<bound method Command.Run of <googlecloudsdk.calliope.backend.Command object at 0x109e70b10>>, command_path=['gcloud', 'preview', 'app', 'run'], datastore_consistency_policy='time', datastore_path=None, default_gcs_bucket_name=None, enable_cloud_datastore=False, enable_mvm_logs=False, enable_sendmail=False, format=None, h=None, help=None, host=None, http_timeout=None, jvm_flag=None, log_http=None, log_level='debug', logs_path=None, markdown=None, max_module_instances=None, php_executable_path=None, project='wildstarservicedesk-hrd', python_startup_script=None, quiet=None, require_indexes=False, runnables=['/Users/derekberube/Documents/Programming/Java/Wildstar ServiceDesk Maven/target/servicedesk-1.0-SNAPSHOT'], show_mail_body=False, smtp_allow_tls=False, smtp_host=None, smtp_password=None, smtp_user=None, storage_path=None, trace_token=None, use_mtime_file_watcher=False, user_output_enabled=None, verbosity='debug', version=None).
[INFO] ERROR: Directories are not supported [/Users/derekberube/Documents/Programming/Java/Wildstar ServiceDesk Maven/target/servicedesk-1.0-SNAPSHOT].  You must provide explicit yaml files.
[INFO] DEBUG: (gcloud.preview.app.run) Errors occurred while parsing the App Engine app configuration.
[INFO] Traceback (most recent call last):
[INFO]   File "/Users/derekberube/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 617, in Execute
[INFO]     result = args.cmd_func(cli=self, args=args)
[INFO]   File "/Users/derekberube/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 1110, in Run
[INFO]     result = command_instance.Run(args)
[INFO]   File "/Users/derekberube/google-cloud-sdk/lib/googlecloudsdk/calliope/exceptions.py", line 86, in TryFunc
[INFO]     return func(*args, **kwargs)
[INFO]   File "/Users/derekberube/google-cloud-sdk/lib/googlecloudsdk/appengine/app_commands/run.py", line 250, in Run
[INFO]     version=None, check_version=False)
[INFO]   File "/Users/derekberube/google-cloud-sdk/lib/googlecloudsdk/appengine/lib/yaml_parsing.py", line 269, in __init__
[INFO]     raise AppConfigSetLoadError()
[INFO] AppConfigSetLoadError: Errors occurred while parsing the App Engine app configuration.
[INFO] ERROR: (gcloud.preview.app.run) Errors occurred while parsing the App Engine app configuration.
[ERROR] Error: gcloud app xxx exit code is: 1

**Comment by ludoch** [comment] 2015-05-06 23:30
I see you are using 1.9.17a which is very old. Underneath, the Cloud SDK
has changed a lot and you now need to upgrade both to latest versions...

gcloud components update

and use the new version of the Maven plugin: 0.9.58.v20150505  (we started
naming it as the cloud SDK version)

**Comment by ludoch** [comment] 2015-05-06 23:36
You might have to adapt your appengine-web.xml by removing the <application> field which is now available as a CLI arg in the cloud SDK or taken from the environment if you do a global

gcloud config set project YOUR_PROJECT

**Comment by derekberube** [comment] 2015-05-07 01:23
Thanks for the super-fast feedback!

**Comment by derekberube** [comment] 2015-05-07 01:51
So the Docker instance started.  Then I stopped it, edited my pom.xml to add in some Unified Expression Language dependencies and tried to re-run the project only to receive the nebulous:

[ERROR] Error: gcloud app xxx exit code is: 1
[ERROR] 
org.apache.maven.plugin.MojoExecutionException: Error: gcloud app xxx exit code is: 1
	at com.google.appengine.gcloudapp.AbstractGcloudMojo.startCommand(AbstractGcloudMojo.java:368)
	at com.google.appengine.gcloudapp.GCloudAppRun.execute(GCloudAppRun.java:302)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

**Comment by derekberube** [comment] 2015-05-07 05:42
I'm still running into situations where mvn gcloud:run DerekBerubesMBP:Wildstar ServiceDesk Maven derekberube$ gcloud version
Google Cloud SDK 0.9.58

alpha 2015.04.09
app 2015.04.29
app-engine-go-darwin-x86_64 1.9.19
app-engine-java 1.9.19
app-engine-python 1.9.19
app-engine-python-extras 1.9.18
beta 2015.04.21
bq 2.0.18
bq-nix 2.0.18
compute 2015.04.29
core 2015.04.29
core-nix 2014.10.20
dns 2015.04.29
gae-java 1.9.19
gae-java-nix 1.9.10
gae-python 2014.05.06
gae-python-launcher-mac 1.9.19
gcloud 2015.04.29
gcloud-extensions-darwin-x86_64 0.15.0
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.12
gsutil-nix 4.6
preview 2015.04.29
sql 2015.04.09

DerekBerubesMBP:Wildstar ServiceDesk Maven derekberube$ gcloud components update

All components are up to date.
DerekBerubesMBP:Wildstar ServiceDesk Maven derekberube$ 

The following is information from my project's pom.xml.

<plugin>
	<groupId>com.google.appengine</groupId>
	<artifactId>gcloud-maven-plugin</artifactId>
	<version>0.9.58.v20150505</version>
	<configuration>
		<log_level>debug</log_level>
	</configuration>
</plugin>

**Comment by ludoch** [comment] 2015-05-07 18:34
Hum...Thanks for the data... It might be a bug in the Cloud SDK, not the Maven plugin...
We filed an internal bug for that.

Meanwhile, it might be some configuration issue on your system... Could you try from a terminal this command? 

gcloud auth login

Thanks!

**Comment by ludoch** [comment] 2015-05-07 18:40
And it this does not work, try:
export NO_GCE_CHECK=True

For now.

**Comment by derekberube** [comment] 2015-05-07 20:04
It does appear that re-running gcloud auth login worked.

**Comment by rferraresi** [comment] 2015-05-25 21:47
I am receiving same issue. gcloud auth login & export NO_GCE_CHECK=True haven't worked for me.

Also tried to with SDK 0.9.58.

richard$ gcloud version
Google Cloud SDK 0.9.61

app 2015.05.19
app-engine-go-darwin-x86_64 1.9.20
app-engine-java 1.9.20
app-engine-python 1.9.20
app-engine-python-extras 1.9.20
bq 2.0.18
bq-nix 2.0.18
compute 2015.05.19
core 2015.05.19
core-nix 2014.10.20
dns 2015.05.19
gae-go 2015.05.19
gae-go-nix 2014.09.10
gae-python 2014.05.06
gae-python-launcher-mac 1.9.20
gcloud 2015.05.19
gcutil 1.16.5
gcutil-nix 1.16.5
gsutil 4.12
gsutil-nix 4.6
kubectl 
kubectl-darwin-x86_64 0.17.0
preview 2015.05.19
sql 2015.05.06

**Comment by ludoch** [comment] 2015-12-10 11:38
Should be addressed in latest Cloud SDK. 
File a new bug if you see more error reporting.

**Closed by ludoch** 2015-12-10 11:38 UTC
